test: &test
  adapter: postgresql
  database: carriewave_direct_example_test
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: carriewave_direct_example_development
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: myapp
  password:
